### ISSUE TITLE
Suggestion:more customization

### ISSUE THREAD

**Issue by devlam** [runway20/PopoverView#12]
is it possible to make it looks like the one in the picture

http://www.iphone3gsystem.fr/wp-content/uploads/2012/11/eurosport.jpg

**Comment by gerry650** [comment]
OCDaysView *daysView = [[OCDaysView alloc] initWithFrame:CGRectMake(0, 0, 150, 100)];
[daysView setMonth:10];
[daysView setYear:2012];
//[PopoverView showPopoverAtPoint:point inView:self.view withContentView:[daysView autorelease] delegate:self];
[PopoverView showPopoverAtPoint:point inView:self.view withTitle:@"October 2012" withContentView:[daysView autorelease] delegate:self];
