### ISSUE TITLE
ios6

### ISSUE THREAD

**Issue by joekh** [runway20/PopoverView#13]
The popover view is not responding for the touch events. The "didSelectItemAtIndex" on ios6, it only responds for index 0, all items above index 0 don't work when you click on them

**Comment by gerry650** [comment]
OCDaysView *daysView = [[OCDaysView alloc] initWithFrame:CGRectMake(0, 0, 150, 100)];
[daysView setMonth:10];
[daysView setYear:2012];
//[PopoverView showPopoverAtPoint:point inView:self.view withContentView:[daysView autorelease] delegate:self];
[PopoverView showPopoverAtPoint:point inView:self.view withTitle:@"October 2012" withContentView:[daysView autorelease] delegate:self];
