### ISSUE TITLE
Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'

### ISSUE THREAD

**Issue by Wirsing84** [runway20/PopoverView#15]
Hello!
PopoverView looks great and we'd really like to use it. However, wherever I add it to our app it crashes with a runtime error during
- (void)showAtPoint:(CGPoint)point inView:(UIView *)view withContentView:(UIView *)cView

The crash happens at this line:
self.frame = topViewBounds;

-> Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'

An NSLog I created above that line retrieves:
Frame: X=nan Y=nan W=0.0 H=0.0 - TopViewBounds: X=0.0 Y=0.0 W=0.0 H=0.0

It seems like there is something wrong with creating the PopoverView's frame.

Running in iOS 5 and iOS6 Simulator.

I appreciate any ideas and help!

**Comment by gerry650** [comment]
OCDaysView *daysView = [[OCDaysView alloc] initWithFrame:CGRectMake(0, 0, 150, 100)];
[daysView setMonth:10];
[daysView setYear:2012];
//[PopoverView showPopoverAtPoint:point inView:self.view withContentView:[daysView autorelease] delegate:self];
[PopoverView showPopoverAtPoint:point inView:self.view withTitle:@"October 2012" withContentView:[daysView autorelease] delegate:self];
