### ISSUE TITLE
Had a problem working with table view in PopOver.

### ISSUE THREAD

**Issue by Dimajp** [runway20/PopoverView#2]
Hi.

Had a problem working with table view in PopOvover. (with latest code)
Resolved by adding changes in this code in your class

```
//Add a tap gesture recognizer to the large invisible view (self), which will detect taps anywhere on the screen.
UITapGestureRecognizer *tap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(tapped:)];
tap.cancelsTouchesInView = NO;// we need this to add possability to enable working witht able view
[self addGestureRecognizer:tap];
[tap release];
```

Actually there is only one line was added :
    tap.cancelsTouchesInView = NO;// we need this to add possability to enable working witht able view

Really hope this will be useful fro you.

Thanks for you Class!!!

**Comment by gerry650** [comment]
OCDaysView *daysView = [[OCDaysView alloc] initWithFrame:CGRectMake(0, 0, 150, 100)];
[daysView setMonth:10];
[daysView setYear:2012];
//[PopoverView showPopoverAtPoint:point inView:self.view withContentView:[daysView autorelease] delegate:self];
[PopoverView showPopoverAtPoint:point inView:self.view withTitle:@"October 2012" withContentView:[daysView autorelease] delegate:self];
