### ISSUE TITLE
Insert UIScrollView with image in PopoverView?

### ISSUE THREAD

**Issue by Piero87** [runway20/PopoverView#3]
Hello, i have tried your PopoverView project today, and i think is really great! I have a question about it, there is a way to insert a UIScrollView with UIImageView?...i want insert in it some Image download from the web and loaded runtime when the user swipe left or right in the PopoverView...it's possible?

**Comment by gerry650** [comment]
OCDaysView *daysView = [[OCDaysView alloc] initWithFrame:CGRectMake(0, 0, 150, 100)];
[daysView setMonth:10];
[daysView setYear:2012];
//[PopoverView showPopoverAtPoint:point inView:self.view withContentView:[daysView autorelease] delegate:self];
[PopoverView showPopoverAtPoint:point inView:self.view withTitle:@"October 2012" withContentView:[daysView autorelease] delegate:self];
