### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Spokane-Dude** [runway20/PopoverView#30]
"...full blog post" link (http://blog.getsherpa.com/blog/2012/09/14/popoverview-a-flexible-modal-content-view-for-ios/) is broken:

404 Not Found

```
Code: NoSuchKey
Message: The specified key does not exist.
Key: blog/2012/09/14/popoverview-a-flexible-modal-content-view-for-ios/index.html
RequestId: D7C4DD86CCBDBC14
HostId: bxXuqQuubNRnJcjM9kIEQbuy40Q3Ia2QBLXxwGvuRf2tFu5GIHjufMndydLzQrzj
```

An Error Occurred While Attempting to Retrieve a Custom Error Document

```
Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html
```

**Comment by gerry650** [comment]
OCDaysView *daysView = [[OCDaysView alloc] initWithFrame:CGRectMake(0, 0, 150, 100)];
[daysView setMonth:10];
[daysView setYear:2012];
//[PopoverView showPopoverAtPoint:point inView:self.view withContentView:[daysView autorelease] delegate:self];
[PopoverView showPopoverAtPoint:point inView:self.view withTitle:@"October 2012" withContentView:[daysView autorelease] delegate:self];
