### ISSUE TITLE
Inserting a TableView from a xib file

### ISSUE THREAD

**Issue by aleufms** [runway20/PopoverView#5]
I found a bug when we try inserting a UITableView from a nib file. I tried to do this:

[[NSBundle mainBundle] loadNibNamed:@"MyTableViewNib" owner:self options:nil]; //My .xib file with UITableView inside it
UITableView *myTableView = [nibs objectAtIndex:0]; //Assuming the tableview is the unique object from the nib
[PopoverView showPopoverAtPoint:CGPointMake(0, 0) inView:self.view withTitle:nil withContentView:myTableView delegate:nil]

The size of the table doubles for unknown reason. The size of container is right.

Screenshot: http://img.photobucket.com/albums/v502/alessandro_ufms/Popoverbug.png

**Comment by gerry650** [comment]
OCDaysView *daysView = [[OCDaysView alloc] initWithFrame:CGRectMake(0, 0, 150, 100)];
[daysView setMonth:10];
[daysView setYear:2012];
//[PopoverView showPopoverAtPoint:point inView:self.view withContentView:[daysView autorelease] delegate:self];
[PopoverView showPopoverAtPoint:point inView:self.view withTitle:@"October 2012" withContentView:[daysView autorelease] delegate:self];
